import ProjectDescription

let workspace = Workspace(
    name: "Pitstop",
    projects: [
        "./",
        "Modules/ChassisUI"
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled
    )
)
